version: "3"
services:
  ctphone-api:
    container_name: ctphone-api
    restart: always
    networks:
      - app-network
    build: .
    ports:
      - "32001:32001"
    links:
      - redis
      - mongo
  mongo:
    image: mongo:7.0.0
    container_name: mongodb_database
    restart: always
    networks:
      - app-network
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
  redis:
    image: redis:6.2.6
    container_name: redis
    networks:
      - app-network
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge

volumes:
  mongo: ~